language: julia
os: linux
julia:
    - 0.4
    - 0.5
    - 0.6
    - nightly
branches:
  only:
    - master
notifications:
    email: false
after_success:
    - julia -e 'cd(Pkg.dir("Linuxbrew")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
